#!/usr/bin/env bash
# Writes a Bash script that configures an Ubuntu server

sed 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts > /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts
